In [145]:
# 2026166390 사애진

In [146]:
import numpy as np

In [147]:
a = np.array([[1,2,3],
              [4,5,6]])

a.shape

(2, 3)

In [148]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [149]:
a[0]

np.int64(1)

In [150]:
a[0]=10
a

array([10,  2,  3,  4,  5,  6])

In [151]:
a[:3]

array([10,  2,  3])

In [152]:
b = a[3:]
b

array([4, 5, 6])

In [153]:
b[0] = 40
a

array([10,  2,  3, 40,  5,  6])

In [154]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [155]:
a[1,3]

np.int64(8)

In [156]:
a.ndim

2

In [157]:
a.shape
len(a.shape) == a.ndim

True

In [158]:
a.size
import math
a.size == math.prod(a.shape)

True

In [159]:
a.dtype

dtype('int64')

In [160]:
np.zeros(2)

array([0., 0.])

In [161]:
np.ones(2)

array([1., 1.])

In [162]:
np.empty(2)

array([1., 1.])

In [163]:
np.arange(4)

array([0, 1, 2, 3])

In [164]:
np.arange(2,9,2)

array([2, 4, 6, 8])

In [165]:
np.linspace(0,10,num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [166]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1])

In [167]:
arr = np.array([2,1,5,3,7,4,6,8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [168]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [169]:
np.concatenate((a,b,))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [170]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6]])

In [171]:
np.concatenate((x,y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [172]:
array_example = np.array([[[0,1,2,3],
                           [4,5,6,7]],

                         [[0,1,2,3],
                          [4,5,6,7]],

                         [[0,1,2,3],
                          [4,5,6,7]]])

In [173]:
array_example.ndim

3

In [174]:
array_example.size

24

In [175]:
array_example.shape

(3, 2, 4)

In [176]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [177]:
b = a.reshape(3,2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [178]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [179]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [180]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [181]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [182]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [183]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [184]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [185]:
data = np.array([1,2,3])

data[1]
data[0:2]
data[1:]
data[-2:]

array([2, 3])

In [186]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [187]:
print(a[a<5])

[1 2 3 4]


In [188]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [189]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [190]:
c = a[(a>2) & (a<11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [191]:
five_up = (a>5) | (a==5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [192]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [193]:
b = np.nonzero(a<5)
print(b)

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))


In [194]:
list_of_coordinates = list(zip(b[0], b[1]))
for coord in list_of_coordinates:
  print(coord)

(np.int64(0), np.int64(0))
(np.int64(0), np.int64(1))
(np.int64(0), np.int64(2))
(np.int64(0), np.int64(3))


In [195]:
print(a[b])

[1 2 3 4]


In [196]:
not_there = np.nonzero(a==42)
print(not_there)

(array([], dtype=int64), array([], dtype=int64))


In [197]:
a = np.array([1,2,3,4,5,6,7,8,9,10])

In [198]:
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [199]:
a1 = np.array([[1,1],
               [2,2]])
a2 = np.array([[3,3],
               [4,4]])

In [200]:
np.vstack((a1,a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [201]:
np.hstack((a1,a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [202]:
x = np.arange(1,25).reshape(2,12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [203]:
np.hsplit(x,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [204]:
np.hsplit(x,(3,4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [205]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [206]:
b1 = a[0,:]
b1
b1[0] = 99
b1
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [207]:
b2 = a.copy()

In [208]:
data = np.array([1,2])
ones = np.ones(2, dtype=int)
data + ones

array([2, 3])

In [209]:
data - ones
data * data
data / data

array([1., 1.])

In [210]:
a = np.array([1,2,3,4])
a.sum()

np.int64(10)

In [211]:
b = np.array([[1,1],[2,2]])

In [212]:
b.sum(axis=0)

array([3, 3])

In [213]:
b.sum(axis=1)

array([2, 4])

In [214]:
data = np.array([1.0,2.0])
data * 1.6

array([1.6, 3.2])

In [215]:
data = np.array([1,2,3])
data.max()
data.min()
data.sum()

np.int64(6)

In [216]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [217]:
a.sum()

np.float64(4.8595784)

In [218]:
a.min()

np.float64(0.05093587)

In [219]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [220]:
data = np.array([[1,2,],[3,4],[5,6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [221]:
data[0,1]
data[1:3]
data[0:2, 0]

array([1, 3])

In [222]:
data.max()
data.min()
data.sum()

np.int64(21)

In [223]:
data = np.array([[1,2],[5,3],[4,6]])
data
data.max(axis=0)
data.max(axis=1)

array([2, 5, 6])

In [224]:
data = np.array([[1,2],[3,4]])
ones = np.array([[1,1],[1,1]])
data + ones

array([[2, 3],
       [4, 5]])

In [225]:
data = np.array([[1,2],[3,4],[5,6]])
ones_row = np.array([[1,1]])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [226]:
np.ones((4,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [227]:
np.ones(3)
np.zeros(3)
rng = np.random.default_rng()
rng.random(3)

array([0.24998561, 0.71510517, 0.26324414])

In [228]:
np.ones((3,2))
np.zeros((3,2))
rng.random((3,2))

array([[0.32512818, 0.73812141],
       [0.52015716, 0.12076247],
       [0.39486796, 0.87691515]])

In [229]:
rng.integers(5, size=(2,4))

array([[0, 3, 1, 0],
       [1, 1, 0, 1]])

In [230]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [231]:
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [232]:
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [233]:
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)

[3 2 2 2 1 1 1 1 1 1]


In [234]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])

In [235]:
unique_values = np.unique(a_2d)
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [236]:
unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [237]:
unique_rows, indices, occurrence_count = np.unique(
     a_2d, axis=0, return_counts=True, return_index=True)
print(unique_rows)
print(indices)
print(occurrence_count)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[0 1 2]
[2 1 1]


In [238]:
data.reshape(2, 3)
data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [239]:
arr = np.arange(6).reshape((2, 3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [240]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [241]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [242]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [243]:
reversed_arr = np.flip(arr)

In [244]:
print('Reversed Array: ', reversed_arr)

Reversed Array:  [8 7 6 5 4 3 2 1]


In [245]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [246]:
reversed_arr = np.flip(arr_2d)
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [247]:
reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [248]:
reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [249]:
arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [250]:
arr_2d[:,1] = np.flip(arr_2d[:,1])
print(arr_2d)

[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


In [251]:
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [252]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [253]:
a1 = x.flatten()
a1[0] = 99
print(x)
print(a1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[99  2  3  4  5  6  7  8  9 10 11 12]


In [254]:
a2 = x.ravel()
a2[0] = 98
print(x)
print(a2)

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[98  2  3  4  5  6  7  8  9 10 11 12]
